version: "3"
services:
  mlflow-server:
    container_name: mlflow-server
    build: ./mlflow/
    ports:
      - "5000:5000"
    networks:
      - mlde-net
    volumes:
      - ./mlflow-data:/mlflow
  python-apps:
    container_name: python-apps
    build: ./python-apps/
    ports:
      - "4200:4200"
      - "5001:5001"
    networks:
      - mlde-net
    volumes:
      - ../code/:/usr/src/app/code
    depends_on:
      mlflow-server:
        condition: service_started

networks:
  mlde-net:
    driver: bridge
